### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by Lodek** [GoogleCloudPlatform/kms-integrations#3]
Greetings,

From the `README.md` and `BUILDING.md`, it seems like there is no build support for ARM64 and it would be on a best effort basis.
I tried compiling the libkmsp11 and ran into a [failed assertion](https://github.com/GoogleCloudPlatform/kms-integrations/blob/master/kmsp11/util/platform_posix.cc#L73).

I am wondering whether there's some limitation that would cause the lib to absolutely break on an arm64 system or whether this assertion was a safety net?
Do you have any estimate on how difficult it would be to add support for arm64?

Any suggestions on what I'd need to modify in order to support it would also be greatly appreciated.

Regards.

**Comment by bdhess** [comment]
Hey! -- This assertion is indeed just a safety net.

With [a few tweaks](https://github.com/bdhess/kms-integrations/commit/aa38602b03c1f3368a0ede2533c3fa4a5404acc9.patch) I was able to get the library to compile and all the tests to pass on an M1 Mac.  I think I can give it a try on aarch64 Linux sometime next week just to see what happens, but I don't think it should be too much of a lift to get it to work.

**Comment by bdhess** [comment]
Turns out there was [another minor patch](https://github.com/bdhess/kms-integrations/commit/7fd6fed6d45823dcd371e4116f1971713641eff7.patch) needed to update one of our dependencies.  With the combination of this patch and the previous one I mentioned, I built and executed all tests successfully on Ubuntu 20.04 arm64.

Moving forward we'll try to get these patches integrated.  Internally we need to put them through CI on all platforms.  Informally, even though we don't officially support arm64, after the next round of dependency updates and the upcoming 1.1 release, I'd be surprised if arm64 breaks.  There's a lot more eyes on it now that developers actually have arm64 hardware with M1.

**Comment by Lodek** [comment]
The last patched worked liked a charm!

I was struggling with the Abseil compilation errors but now everything ran smoothly!

There are two little things that I'd like to point out:
1. There is a missing character for the package checksum in the last patch you linked. The sha should start with a `d`. (ie `dcf71b9cba8dc0ca9940c4b316a0c796be8fab42b070bb6b7cab62b48f0e66c4` instead of `cf71b9cba8dc0ca9940c4b316a0c796be8fab42b070bb6b7cab62b48f0e66c4`)
2. In `BUILDING.md` it is said that the project can be built using Bazel 4.0 or later. I tried with Bazel 5.0 and ran into some problems regarding. After building using Bazel version to 4.0, everything ran smoothly. This is my first contact with Bazel so it might very well be something I was doing wrong.

Awesome stuff, thanks a ton!
