### ISSUE TITLE
need for GRPC_ENABLE_FORK_SUPPORT=1 when used in applications that fork

### ISSUE THREAD

**Issue by selvanair** [GoogleCloudPlatform/kms-integrations#37]
For many applications (e.g., apache2, OpenVPN) use of this pkcs11 module for private keys in KMS requires to set GRPC_ENABLE_FORK_SUPPORT=1. Would it be possible to make this a configuration option? Users anyway need to setup a config file, would be easier if the fork support also could be enabled at the same place.

**Comment by tdbhacks** [comment]
Apologies for the late reply, I was sure I had replied a while back but never did!

I'm not super convinced this would be a very helpful config option just because setting the config itself also relies on an environment variable (`KMS_PKCS11_CONFIG`), so `GRPC_ENABLE_FORK_SUPPORT` can easily be set at the same time / in the same file. eg. for apache, this new config option would just save 1 line in `/etc/apache2/envvars`

Let me know if I'm missing anything though.
